### ISSUE TITLE
Compile

### ISSUE THREAD

**Issue by ghost** [Hinco01/BitmexBot_Goran#1]
Can you compile it and post in the releases?

**Comment by Hinco01** [comment]
I still did not add a possibility to enter your API keys... So it would be of no use to you right now if I compile it.

**Comment by ghost** [comment]
And if I send them to you, will you compile it for me?

**Comment by ghost** [comment]
Hello. So, I started a VPS, installed Microsoft Visual Studio Community version 2017, opened the project and it looks like working. Now, I just have to change the keys, click Start, click switch, click Start and it will automatically start buying and selling (trading)?

**Comment by ghost** [comment]
Small problem, look -

**Comment by ghost** [comment]
![capture](https://user-images.githubusercontent.com/39766692/43407202-983a93a4-940d-11e8-9719-acfce9fb1afe.PNG)

**Comment by ghost** [comment]
I would be really happy if you compiled it and sent to me. There are the keys on TestNet at the moment.

Key 4vWNTsajQWK1K7NzDHF809bW
Secret ezDf9HWU5TsjMiUaSV0V1QDvToJif9AqjLKeKjI5ueV18Z31

**Comment by Hinco01** [comment]
I'm on holidays for two weeks. I will only be able to check it after I'm back

**Comment by ghost** [comment]
Okay, thanks, let me know then

**Comment by Hinco01** [comment]
I did some new updates.
You still need to add your API key and secret into the code and compile.
It will start with LIVE BitMex server. 
If you want it to start with Test server change in the code (Form1.cs)

ddNetwork.SelectedIndex = 1; 
to
ddNetwork.SelectedIndex = 0;

I left it to run overnight on production and it did 10 trades with 0,5 % earning each... not much but it piles up.

**Comment by ghost** [comment]
Here are my API keys (Test Server). Please, can you compile it for me and send it here? I have got only 500 MB space on my hard drive and my internet connection speed is not very fast to download Visual Studio.

Key - CYAU5MEgpudyIJ6DmnOTIJ8O
Secret - KWlkHuSABPXQlhxN9Pvt_VwCJSdKHwYWXisnIovO0_C6vtBR

**Comment by 1221328** [comment]
Hello, I am trying it on VPS at the moment but I can not find ddNetwork.SelectedIndex in the code.

**Comment by ghost** [comment]
Error. Edited API keys and ddNetwork.

**Comment by ghost** [comment]
![capture](https://user-images.githubusercontent.com/39766692/44231398-8ba35d00-a18d-11e8-9813-270c99665ff3.PNG)

**Comment by Hinco01** [comment]
Give me your mail and I will send it to you

**Comment by ghost** [comment]
1221328@protonmail.com

Thank you.

**Comment by Hinco01** [comment]
sent

**Comment by ghost** [comment]
Thanks. I am going to try it and let you know then.

**Comment by Hinco01** [comment]
added a new version and put it in the release
