### ISSUE TITLE
Strat 3 works / need logging

### ISSUE THREAD

**Issue by Dycast** [Hinco01/BitmexBot_Goran#11]
Hey, been messin with this got newest ver. and src switched src over to testnet and after makin a change to indicators have strat 3 working, haven't tried changing,leverage but will..

strat 1 and 2 i can't get to work (hrs of lettin it run)

would be great to have the output dump to a log file, it's been a long time since i've programmed, but will try to keep helping out, this has the  best potential towards what i'm wanting that i've been able to find..

keep it up!

**Comment by Hinco01** [comment]
https://botgas.webstarts.com/
